### ISSUE TITLE
Raid registering issue tracker

### ISSUE THREAD

**Issue by maximeroucher** [aeecleclair/Hyperion#524]
Since we want to publish as soon as possible, some things can be improved after, here is the list :
- T-Shirt on participant update
- Adding missing tests to improve coverage
- Foreign key constraint violation on update security file
- Adding delete all team button
- Restricting  file size

**Comment by armanddidierjean** [comment]
500 for `raid/security_file/?participant_id=` when updating security file:
```
sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.ForeignKeyViolationError'>: update or delete on table "raid_security_file" violates foreign key constraint "raid_participant_security_file_id_fkey" on table "raid_participant"
```

**Comment by armanddidierjean** [comment]
```
Error while creating pdf Traceback (most recent call last): File "/app/app/modules/raid/utils/utils_[raid.py](http://raid.py/)", line 142, in save_team_info file_path = pdf_writer.write_team(team) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/app/modules/raid/utils/pdf/pdf_[writer.py](http://writer.py/)", line 114, in write_team return self.add_pdf() ^^^^^^^^^^^^^^ File "/app/app/modules/raid/utils/pdf/pdf_[writer.py](http://writer.py/)", line 76, in add_pdf writer.write("data/raid/" + self.file_name) File "/usr/local/lib/python3.11/site-packages/pypdf/_[writer.py](http://writer.py/)", line 1274, in write stream = FileIO(stream, "wb") ^^^^^^^^^^^^^^^^^^^^ FileNotFoundError: [Errno 2] No such file or directory: data/raid/Équipe de xxxx.pdf
